import numpy as np 

# Simulation configuration
BASE_LEN_X = 10
BASE_LEN_Y = 10
NUM_CHAINS = 50
CHAIN_LEN = 10
SPRING_START_LENGTH = 1
PRECISION = np.float64
ITERATIONS_BETWEEN_SAVES = 1000
TIMES_TO_SAVE = 100 # total iterations: 1000 * 100 = 10^5
STARTING_CONFIGURATIONS = 10

# Physical constants
K_SPRING = 1
C_INTERACTIONS = [0.5,1]
TEMPERATURES = [0.5,1,2]
R_SIZE = 1 
SURFACE_INTERACTION_ENERGY = 1e9
DENSITY_CALC_Z_BOUNDARY = 2

DENSITY_VOLUME = BASE_LEN_Y * BASE_LEN_X * DENSITY_CALC_Z_BOUNDARY


# Output
RESULTS_FOLDERNAME = 'results' 
CSV_FILENAME = f'{RESULTS_FOLDERNAME}/simulation_results.csv'
GRAPH_TITLE = 'Surface Density against Steps'